# Generated by Django 4.0.3 on 2022-03-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
